spring:
  application:
    name: auth-server
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:homelab}
  client-id: ${KEYCLOAK_CLIENT_ID:auth-server-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
